import { useEffect, useState } from 'react'
import type { GPU, Model, ReserveProfile } from '../types/schema'
import { loadModels } from '../models/data'
import { loadGpus } from '../hardware/data'
import { simulate } from '../simulator/simulate'
import { Field, NumberField } from '../components/Field'
import { MemoryChart } from '../components/MemoryChart'
import { ModelDetail } from '../models/ModelDetail'
import { ModelSearch } from '../models/ModelSearch'
import { ComparisonTable } from '../comparison/ComparisonTable'
import { gib } from '../utils/format'

const defaults = { contextLength: 8192, concurrency: 1, inputTokens: 1024, outputTokens: 512, gpuCount: 8, nodeCount: 1, tp: 8, dp: 1, pp: 1, ep: 1, reserveProfile: 'balanced' as ReserveProfile }
export function App() {
  const [models, setModels] = useState<Model[]>([]), [gpus, setGpus] = useState<GPU[]>([]), [errors, setErrors] = useState<string[]>([]), [loading, setLoading] = useState(true)
  const [modelId, setModelId] = useState(''), [variantId, setVariantId] = useState(''), [gpuAId, setGpuAId] = useState(''), [gpuBId, setGpuBId] = useState('')
  const [config, setConfig] = useState(defaults), [detail, setDetail] = useState(false)
  useEffect(() => { Promise.all([loadModels(), loadGpus()]).then(([m, g]) => { setModels(m.models); setGpus(g.gpus); setErrors([...m.errors, ...g.errors]); setModelId(m.models[0]?.model_id ?? ''); setVariantId(m.models[0]?.variants[0]?.variant_id ?? ''); setGpuAId(g.gpus[0]?.gpu_id ?? ''); setGpuBId(g.gpus[1]?.gpu_id ?? g.gpus[0]?.gpu_id ?? '') }).catch((error) => setErrors([String(error)])).finally(() => setLoading(false)) }, [])
  const model = models.find((item) => item.model_id === modelId) ?? models[0]
  const variant = model?.variants.find((item) => item.variant_id === variantId) ?? model?.variants[0]
  const gpuA = gpus.find((item) => item.gpu_id === gpuAId) ?? gpus[0], gpuB = gpus.find((item) => item.gpu_id === gpuBId) ?? gpus[1] ?? gpus[0]
  const make = (gpu: GPU) => simulate({ model, variant, gpu, ...config })
  const resultA = model && variant && gpuA ? make(gpuA) : null, resultB = model && variant && gpuB ? make(gpuB) : null
  const set = <K extends keyof typeof config>(key: K, value: (typeof config)[K]) => setConfig((current) => ({ ...current, [key]: value }))
  const selectModel = (next: Model) => { setModelId(next.model_id); setVariantId(next.variants[0]?.variant_id ?? '') }
  if (loading) return <main className="loading">正在校验并加载静态数据…</main>
  return <><header><div><a className="brand" href="/ai-infra-wiki/">柏源 Infra</a><span className="divider"/><strong>AI Infra Simulator</strong></div><a href="/ai-infra-wiki/">← 返回知识库</a></header><main>
    <section className="intro"><p className="eyebrow">MODEL × GPU × MEMORY × INTERCONNECT × PARALLELISM</p><h1>部署可行性与理论瓶颈分析</h1><p>浏览器本地计算 · 不生成虚假 Benchmark · 理论值与估算值明确标注</p></section>{errors.length > 0 && <aside className="warning">部分脏数据已隔离：{errors.join('；')}</aside>}
    <div className="workbench"><section className="panel"><div className="panel-title"><h2>01 模型配置</h2><span className="tag source">静态数据</span></div>
      <ModelSearch models={models} selectedId={modelId} onSelect={selectModel}/><Field label="当前模型"><select value={modelId} onChange={(event) => { const next = models.find((item) => item.model_id === event.target.value); if (next) selectModel(next) }}>{models.map((item) => <option key={item.model_id} value={item.model_id}>{item.display_name} · {item.moe ? 'MoE' : 'Dense'}</option>)}</select></Field>
      {model && <Field label="Checkpoint / Weight Precision"><select value={variant?.variant_id} onChange={(event) => setVariantId(event.target.value)}>{model.variants.map((item) => <option key={item.variant_id} value={item.variant_id}>{item.checkpoint} · {item.weight_dtype}{item.quantization_method && item.quantization_method !== 'none' ? ` · ${item.quantization_method}` : ''}</option>)}</select></Field>}
      <NumberField label="Context Length" value={config.contextLength} onChange={(value) => set('contextLength', value)}/><NumberField label="Input Tokens" value={config.inputTokens} onChange={(value) => set('inputTokens', value)}/><NumberField label="Output Tokens" value={config.outputTokens} onChange={(value) => set('outputTokens', value)}/><NumberField label="Concurrency" value={config.concurrency} onChange={(value) => set('concurrency', value)}/><button className="secondary" onClick={() => setDetail(true)}>查看模型详情</button></section>
      <section className="panel"><div className="panel-title"><h2>02 硬件配置</h2><span className="tag source">已验证来源</span></div><Field label="Configuration A · GPU"><select value={gpuAId} onChange={(event) => setGpuAId(event.target.value)}>{gpus.map((gpu) => <option value={gpu.gpu_id} key={gpu.gpu_id}>{gpu.vendor} {gpu.model}</option>)}</select></Field><Field label="Configuration B · GPU"><select value={gpuBId} onChange={(event) => setGpuBId(event.target.value)}>{gpus.map((gpu) => <option value={gpu.gpu_id} key={gpu.gpu_id}>{gpu.vendor} {gpu.model}</option>)}</select></Field><div className="grid2"><NumberField label="GPU Count" value={config.gpuCount} onChange={(value) => set('gpuCount', value)}/><NumberField label="Node Count" value={config.nodeCount} onChange={(value) => set('nodeCount', value)}/><NumberField label="TP" value={config.tp} onChange={(value) => set('tp', value)}/><NumberField label="DP" value={config.dp} onChange={(value) => set('dp', value)}/><NumberField label="PP" value={config.pp} onChange={(value) => set('pp', value)}/><NumberField label="EP" value={config.ep} onChange={(value) => set('ep', value)}/></div><Field label="Memory Reserve"><select value={config.reserveProfile} onChange={(event) => set('reserveProfile', event.target.value as ReserveProfile)}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></Field><dl className="hardware-facts"><div><dt>GPU Memory</dt><dd>{gib(gpuA?.memory_gb)}</dd></div><div><dt>Interconnect</dt><dd>{gpuA?.interconnect_type ?? 'N/A'}</dd></div><div><dt>Network</dt><dd>用户环境未提供</dd></div></dl></section>
      <section className="panel results"><div className="panel-title"><h2>03 Simulation Result</h2><span className="tag estimated">理论 / 估算</span></div>{resultA && <><div className={`status ${resultA.fit?.canRun ? 'ok' : 'no'}`}><small>DEPLOYMENT · CONFIGURATION A</small><strong>{resultA.fit?.canRun ? '✓ Can Run' : '× Cannot Run / Unknown'}</strong></div><Metric label="Theoretical Weight" value={gib(resultA.weight.theoreticalGiB)}/><Metric label="Deployment Weight" value={gib(resultA.weight.deploymentGiB)}/><Metric label="KV Cache" value={gib(resultA.kv.gib)} note={resultA.kv.missing.length ? `缺少 ${resultA.kv.missing.join(', ')}` : undefined}/><Metric label="Runtime Reserve" value={gib(resultA.total?.runtimeReserveGiB)}/><Metric label="Framework Overhead" value={gib(resultA.total?.frameworkOverheadGiB)}/><Metric label="Required Memory" value={gib(resultA.total?.requiredGiB)}/><Metric label="Available Memory" value={gib(resultA.fit?.availableGiB)}/><Metric label="Memory Utilization" value={resultA.fit ? `${(resultA.fit.utilization * 100).toFixed(1)}%` : 'N/A'}/><Metric label="Bottleneck" value={resultA.bottleneck}/><div className="recommend"><b>Recommended Candidate</b><p>{resultA.recommendation}</p></div><div className="benchmark"><b>Benchmark</b><p>暂无实测 Benchmark</p></div></>}</section></div>
    {resultA?.total && resultA.weight.deploymentGiB != null && resultA.kv.gib != null && <section className="panel compare"><div className="panel-title"><h2>Memory Composition</h2><span className="tag estimated">ECharts · 估算</span></div><MemoryChart weight={resultA.weight.deploymentGiB} kv={resultA.kv.gib} runtime={resultA.total.runtimeReserveGiB} framework={resultA.total.frameworkOverheadGiB}/></section>}{resultA && resultB && gpuA && gpuB && <ComparisonTable a={resultA} b={resultB} gpuA={gpuA} gpuB={gpuB} countA={config.gpuCount} countB={config.gpuCount}/>}<p className="disclaimer">本工具给出理论计算与工程预留估算，不构成特定框架的性能承诺。实际部署需验证量化格式、算子支持、拓扑、通信和服务框架。</p>
  </main>{detail && model && variant && <ModelDetail model={model} variant={variant} onClose={() => setDetail(false)}/>}</>
}
function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div> }
